### ISSUE TITLE
customProperties e.entries is not a function

### ISSUE THREAD

**Issue by thanoseleftherakos** [ebess/advanced-nova-media-library#66] opened 2019-04-08 18:44 UTC
Hello,
Im trying to add a custom property to a multiple image field, when I hit the update button nothing happens and in the console I'm getting the following error:

`
TypeError: e.entries is not a function
    at a.handleUpdate (media-lib-images-field:1)
    at a.e (vendor.js?id=b30263b2f9d68433c3ce:1)
    at a.I3G/.t.$emit (vendor.js?id=b30263b2f9d68433c3ce:1)
    at a.handleUpdate (media-lib-images-field:1)
    at submit (media-lib-images-field:1)
    at e (vendor.js?id=b30263b2f9d68433c3ce:1)
    at HTMLFormElement.Yr.e._withTask.o._withTask (vendor.js?id=b30263b2f9d68433c3ce:1)
`

Anyone else facing the same problem?

**Comment by ebess** [comment] 2019-04-19 14:29
@thanoseleftherakos 
Please provide your config on the field.

**Comment by thanoseleftherakos** [comment] 2019-04-19 14:49
Hello, thank you very much for your reply.
Below is my nova resource:
```
namespace App\Nova;
use Laravel\Nova\Fields\ID;
use Illuminate\Http\Request;
use Spatie\NovaTranslatable\Translatable;
use MrMonat\Translatable\Translatable as TranslatableTabs;
use Benjaminhirsch\NovaSlugField\Slug;
use Benjaminhirsch\NovaSlugField\TextWithSlug;
use Arsenaltech\NovaTab\NovaTab;
use Laravel\Nova\Fields\Text;
use Laravel\Nova\Fields\Number;
use Laravel\Nova\Fields\BelongsTo;
use Laravel\Nova\Fields\HasMany;
use NovaAttachMany\AttachMany;
use Yassi\NestedForm\NestedForm;
use Naxon\NovaFieldSortable\Concerns\SortsIndexEntries;
use Naxon\NovaFieldSortable\Sortable;
use Ebess\AdvancedNovaMediaLibrary\Fields\Images;
class Tour extends Resource
{
    /**
     * The model the resource corresponds to.
     *
     * @var string
     */
    public static $model = 'App\Tour';

    use SortsIndexEntries;
    public static $defaultSortField = 'sort_order';

    /**
     * The single value that should be used to represent the resource when being displayed.
     *
     * @var string
     */
    public static $title = 'title';

    /**
     * The columns that should be searched.
     *
     * @var array
     */
    public static $search = [
        'id', 'title'
    ];

    public static $group = "Tours";
    public static function label() { return 'Tours'; }

    /**
     * Get the fields displayed by the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function fields(Request $request)
    {
        return [
            ID::make()->sortable()->hideFromIndex(),
            new NovaTab('Basic Info', [
                Translatable::make([ 
                    TextWithSlug::make('Title')->sortable()->rules('max:255')->slug('Slug'),
                    Slug::make('Slug')->rules('max:255', 'unique:tours,slug')->hideFromIndex(),
                ]),
            ]),
            TranslatableTabs::make('Content')->trix()->rules('required')->hideFromIndex(),
            TranslatableTabs::make('Excerpt')->hideFromIndex(),
            TranslatableTabs::make('Highlights')->trix()->rules('required')->hideFromIndex(),
            TranslatableTabs::make('Inclusions')->trix()->rules('required')->hideFromIndex(),
            TranslatableTabs::make('Details')->trix()->rules('required')->hideFromIndex(),
            // TranslatableTabs::make('Inclusions List')->trix()->rules('required')->hideFromIndex(),
            new NovaTab('Specs', [ 
                Text::make('Code')->rules('required', 'max:255'),
                Text::make('Languages')->hideFromIndex(),
                Number::make('Max Persons')->min(1)->max(8)->rules('required','integer', 'min:1')->hideFromIndex(),
                BelongsTo::make('Tour Type', 'type')->rules('required'),
                BelongsTo::make('Tour Destination', 'destination')->rules('required'),
                BelongsTo::make('Tour Duration', 'duration')->rules('required'),
                AttachMany::make('Tour Interests', 'interests'),
                HasMany::make('TourAddons', 'addons')
            ]),
            new NovaTab('Gallery', [ 
                Images::make('Main image', 'main')
                    ->conversion('medium') // conversion used to display the "original" image
                    ->conversionOnView('thumb') // conversion used on the model's view
                    ->thumbnail('thumb'), // conversion used to display the image on the model's index page

                Images::make('Gallery', 'gallery')
                    ->conversion('medium') // conversion used to display the "original" image
                    ->conversionOnView('thumb') // conversion used on the model's view
                    ->thumbnail('thumb') // conversion used to display the image on the model's index page
                    ->multiple()
                    ->customPropertiesFields([
                        Text::make('Description')
                    ])
                    ->hideFromIndex(),
            ]),
            new NovaTab('Prices', [
                NestedForm::make('TourPrices', 'tourprices','App\Nova\TourPrice')->open(true),
                HasMany::make('TourPrices', 'tourprices', 'App\Nova\TourPrice')
            ]),
            new NovaTab('Addons', [
                NestedForm::make('TourAddons', 'addons')->open(true),
                HasMany::make('TourAddons', 'addons')
            ]),
            Sortable::make('Sort Order', 'id')->onlyOnIndex()


            
        ];
    }

    /**
     * Get the cards available for the request.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function cards(Request $request)
    {
        return [];
    }

    /**
     * Get the filters available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function filters(Request $request)
    {
        return [
            new Filters\TourType,
            new Filters\TourDestination,
            new Filters\TourDuration,
        ];
    }

    /**
     * Get the lenses available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function lenses(Request $request)
    {
        return [];
    }

    /**
     * Get the actions available for the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function actions(Request $request)
    {
        return [];
    }
}
```

I've also tried to remove all the other fields and keep only:
```
 Images::make('Gallery', 'gallery')
                    ->conversion('medium') // conversion used to display the "original" image
                    ->conversionOnView('thumb') // conversion used on the model's view
                    ->thumbnail('thumb') // conversion used to display the image on the model's index page
                    ->multiple()
                    ->customPropertiesFields([
                        Text::make('Description')
                    ])
                    ->hideFromIndex(),
```

but same error

**Comment by thanoseleftherakos** [comment] 2019-04-21 08:48
I investigated a bit more and the error is here:

```
vendor.js:94700 [Vue warn]: Error in v-on handler: "TypeError: e.entries is not a function"
found in
---> <CustomPropertiesModal>
       <Root>
```
So maybe something with the component name in this nova function?

`formatComponentName`

**Comment by ebess** [comment] 2019-04-21 10:34
It seems like the custom field configuration is not passed properly to the modal. But, I cannot reproduce it. I even tried the nova tab package. Working fine for me.

**Comment by Kturva** [comment] 2019-04-22 18:33
I also had to comment out 
```
            // fill custom properties for existing media
            // $this->fillCustomPropertiesFromRequest($request, $model, $attribute);
```
from `Media.php` to not get stuck on the same error. That helps me as I'm not currently using custom properties.

**Comment by Chema-TM** [comment] 2019-05-07 11:38
I've got a similiar error and it's imposible to edit custom properties, not working for me.

Chrome console displays the next error message:

```
TypeError: e.entries is not a function
    at a.handleUpdate (media-lib-images-field:1)
    at a.e (vendor.js?id=b30263b2f9d68433c3ce:1)
    at a.I3G/.t.$emit (vendor.js?id=b30263b2f9d68433c3ce:1)
    at a.handleUpdate (media-lib-images-field:1)
    at submit (media-lib-images-field:1)
    at e (vendor.js?id=b30263b2f9d68433c3ce:1)
    at HTMLFormElement.Yr.e._withTask.o._withTask (vendor.js?id=b30263b2f9d68433c3ce:1)
```

**Comment by thanoseleftherakos** [comment] 2019-05-22 12:18
Just found out that if I change
`for (let [property, value] of formData.entries())` to
`for (let [property, value] of formData.entries) {`
works fine

**Comment by ArmeniaH** [comment] 2019-07-08 23:04
Any news about this ? This is an issue with browser implementations of Form Data
Only firefox developer editions supports formData.entries()
Other browsers does not have that function, and as mentioned above, the property of that object should be used ```formData.entries``` instead of ```formData.entries()```

**Comment by ArmeniaH** [comment] 2019-07-16 18:28
any news on this ?

**Comment by Chema-TM** [comment] 2019-08-27 13:38
> I've got a similiar error and it's imposible to edit custom properties, not working for me.
> 
> Chrome console displays the following error message:
> 
> ```
> TypeError: e.entries is not a function
>     at a.handleUpdate (media-lib-images-field:1)
>     at a.e (vendor.js?id=b30263b2f9d68433c3ce:1)
>     at a.I3G/.t.$emit (vendor.js?id=b30263b2f9d68433c3ce:1)
>     at a.handleUpdate (media-lib-images-field:1)
>     at submit (media-lib-images-field:1)
>     at e (vendor.js?id=b30263b2f9d68433c3ce:1)
>     at HTMLFormElement.Yr.e._withTask.o._withTask (vendor.js?id=b30263b2f9d68433c3ce:1)
> ```

Hello again,

In reference to my old comment, finally I found the problem. In my case is an incompatibility with nova-scroll-top package. I removed it and now custom properties work perfect.

Thanks to @ebess for your amazing work

**Comment by ebess** [comment] 2019-09-04 13:31
@ArmeniaH Is it the same reason for you?

**Comment by ebess** [comment] 2019-09-04 13:54
I will close this for now. I just can not reproduce!

**Closed by ebess** 2019-09-04 13:54 UTC
Labels: bug

**Comment by ArmeniaH** [comment] 2019-10-26 00:47
@Chema-TM Hi mate, do you know what exactly was causing this issue ?
I am not using that package, but maybe some other package causing the problem.

I am still having the issue.

**Comment by armeniax** [comment] 2021-01-16 02:54
@ebess 

I still have this issue on 3.4.0 version on Mac Firefox. I don't use other package conflicting.

TypeError: t.entries is not a function
handleUpdate /nova-api/scripts/media-lib-images-field:1
